version : "3.7"

services:

  app:
    build: ./
    container_name: deep-learning-production
    restart: always
    volumes:
      - ./:/app
    expose:
      - 5000

  nginx:
    build: ../nginx
    container_name: nginx
    restart: always
    ports:
      - "5000:80"